on: pull_request

name: Fluent-linter
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: fluent_linter_action
        uses: calyptia/fluent-linter-action@v0.1.0
        with:
          CALYPTIA_API_KEY: ${{ secrets.CALYPTIA_API_KEY }}
          CONFIG_LOCATION_GLOB: 'fluent-bit.conf'
